### ISSUE TITLE
 Migrate off camlp4

### ISSUE THREAD

**Issue by XVilka** [gasche/bisect#2]
Camlp4 is deprecated for a long time, Camlp5 as well. It makes sense either migrate to mehrir, or extension points for preprocessing and parsing capabilities.

See discussion about Camlp4, Camlp5, Ulex and modern OCaml here: https://discuss.ocaml.org/t/camlp5-and-ocaml-4-08/3985

Also it makes sense to switch to Dune build system as well, plus adding a CI scripts.

**Comment by gasche** [comment]
There already exists a port to attributes and extension points, [bisect_ppx](https://github.com/aantron/bisect_ppx). The venerable `bisect` should not be used for new projects for the reason you give, and for me it's enough that we keep it working for old packages that use it to still work, when they can, on new OCaml versions.

**Comment by XVilka** [comment]
Ah, my bad then. Sorry for the noise. Probably it should be mentioned in README then.

**Comment by gasche** [comment]
Sure, would you send a pull request?

**Comment by gasche** [comment]
I merged the deprecation warning, and will close this issue. Thanks for your work!
